name: Setup-Java
on: push
jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - run: java --version
